
GET http://localhost:8080/properties
###


POST http://localhost:8080/property
Content-Type: application/json

{
    "title": "Villa Super Lux Lo2ta",
    "project": "Cairo Festival City",
    "developer": "Safwa",
    "delivery_date": "10-01-2049",
    "owner":{
        "name": "Ahmed Shobeer",
        "phone_number": "53533"
    },
    "type":"studio",
    "city": 55,
    "size": 305 ,
    "price": 2000000,
    "bathrooms": 3,
    "bedrooms": 2,
    "details": "wallahi sha2a gamda hat3gbak awi"
    
}

###

DELETE   http://localhost:8080/property/642c9290cfd2c59a9f49e0e7
###

GET   http://localhost:8080/property/64288b43745ae1919648f9d
###

PUT   http://localhost:8080/property/64288b43a745ae19196948f9d
Content-Type: application/json

{
    "images":["https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg"]
}